# Generated by Django 5.2.17 on 2026-09-10 09:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_job_id', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=240)),
                ('company', models.CharField(max_length=240)),
                ('location', models.CharField(blank=True, max_length=240)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('salary_is_employer_listed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('match_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_reasoning', models.TextField(blank=True)),
                ('career_alignment', models.CharField(choices=[('strong_match', 'Strong Match'), ('lateral', 'Lateral'), ('entry_level_shift', 'Entry-Level Shift'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('normalized_fingerprint', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider_key', models.CharField(max_length=80, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('discover_jobs', 'Discover Jobs'), ('inspect_job', 'Inspect Job'), ('apply_to_job', 'Apply To Job'), ('classify_correspondence', 'Classify Correspondence'), ('draft_followup', 'Draft Follow-Up')], max_length=40)),
                ('provider', models.CharField(max_length=80)),
                ('provider_task_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timed_out', 'Timed Out'), ('action_required', 'Action Required')], default='pending', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('discovered', 'Discovered'), ('scored', 'Scored'), ('queued', 'Queued'), ('applying', 'Applying'), ('applied', 'Applied'), ('awaiting_response', 'Awaiting Response'), ('action_required', 'Action Required'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed'), ('failed', 'Failed')], default='discovered', max_length=30)),
                ('auto_submit_authorized', models.BooleanField(default=False)),
                ('action_required_reason', models.TextField(blank=True)),
                ('last_state_change_at', models.DateTimeField(auto_now_add=True)),
                ('search_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='profiles.searchpreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('action_required', 'Action Required'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=30)),
                ('provider_task_id', models.CharField(blank=True, max_length=160)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobs.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('unknown', 'Unknown'), ('recruiter_response', 'Recruiter Response'), ('interview_invite', 'Interview Invite'), ('rejection', 'Rejection'), ('additional_info', 'Additional Information')], default='unknown', max_length=40)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='jobs.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('drafted', 'Drafted'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('action_required', 'Action Required')], default='pending', max_length=30)),
                ('draft_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='jobs.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.jobsource'),
        ),
        migrations.CreateModel(
            name='RunSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('max_applications_per_run', models.PositiveSmallIntegerField(default=5)),
                ('min_match_score', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('schedule_start', models.TimeField(blank=True, null=True)),
                ('schedule_end', models.TimeField(blank=True, null=True)),
                ('cadence', models.CharField(blank=True, max_length=40)),
                ('auto_submit', models.BooleanField(default=False)),
                ('linkedin_connected', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'state'], name='jobs_applic_user_id_10c205_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['last_state_change_at'], name='jobs_applic_last_st_39f762_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'title', 'location'], name='jobs_job_company_2d8bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['match_score'], name='jobs_job_match_s_af8c86_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_job_id', ''), _negated=True), fields=('source', 'provider_job_id'), name='unique_provider_job_id_per_source'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_url', ''), _negated=True), fields=('canonical_url',), name='unique_job_canonical_url'),
        ),
    ]
